[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Gas optimization settings
optimizer = true
optimizer_runs = 1000
via_ir = false

[rpc_endpoints]
ethereum_mainnet = "${ETH_MAINNET_RPC_URL}"
optimism_mainnet = "https://mainnet.optimism.io"
base_mainnet = "https://mainnet.base.org"
celo_mainnet = "https://forno.celo.org"
sepolia = "https://rpc.sepolia.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
celo = { key = "${ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }